#
# This file is part of symfinder.
#
# symfinder is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# symfinder is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with symfinder.  If not, see <http://www.gnu.org/licenses/>.
#
# Copyright 2018-2019 Johann Mortara <johann.mortara@etu.univ-cotedazur.fr>
# Copyright 2018-2019 Xhevahire Tërnava <xhevahire.ternava@lip6.fr>
# Copyright 2018-2019 Philippe Collet <philippe.collet@univ-cotedazur.fr>
#

import os
import shutil
import yaml

from mako.template import Template

d3_directory = "d3"
base_directory = "generated_visualizations"


def copy_file(filename):
    shutil.copyfile(os.path.join(d3_directory, filename), os.path.join(base_directory, filename))


copy_file("symfinder.js")
copy_file("style.css")
copy_file("symfinder-icon.png")

xps = {}

with open('symfinder.yaml', 'r') as config_file:
    data = yaml.load(config_file.read(), Loader=yaml.FullLoader)
    with open("experiments/" + data["experimentsFile"], 'r') as experiments_file:
        experiments = yaml.load(experiments_file.read(), Loader=yaml.FullLoader)
        for xp_name, xp_config in experiments.items():
            for id in xp_config.get("tagIds", []) + xp_config.get("commitIds", []):
                xp_codename = (xp_name + "-" + str(id)).replace("/", "_")
                xps[xp_codename] = "./{}.html".format(xp_codename)
                xp_html_file_path = os.path.join(base_directory, "%s.html" % xp_codename)
                with open(xp_html_file_path, 'w+') as output_file:
                    output_file.write(Template(filename=os.path.join(d3_directory, "template.html")).render(
                        title=xp_codename,
                        identifier="{} generated by symfinder version {}".format(xp_codename,
                                                                                 os.getenv("SYMFINDER_VERSION")),
                        jsScriptFile=os.path.join("symfinder.js"),
                        filters=",".join(['"' + f + '"' for f in xp_config.get("filters", [])]),
                        jsonFile=os.path.join("data", "%s.json" % xp_codename),
                        jsonStatsFile=os.path.join("data", "%s-stats.json" % xp_codename))
                    )

with open(os.path.join(base_directory, "index.html"), 'w+') as index_file:
    index_file.write(Template(filename=os.path.join(d3_directory, "index.html")).render(xps=xps))
