%:
	${MAKE} -C macro $@
	${MAKE} -C shape $@
	${MAKE} -C shape-h $@
	${MAKE} -C shape-namespace $@
	${MAKE} -C template-class $@
	${MAKE} -C cpp_strategy $@
	${MAKE} -C multiple-inheritance $@
	${MAKE} -C template-specialization $@